name: HeneriaNPC
version: 1.0
main: fr.heneria.npc.HeneriaNPC
api-version: 1.21
depend: [HeadDatabase]
author: Jules
commands:
  henerianpc:
    description: Commande principale
    permission: heneria.admin
    usage: /henerianpc reload
